events { worker_connections 1024;
}

http {
    # Bloque para el API
    server {
        listen 443 ssl;
        server_name api.sales01.test;

        # USAMOS LAS RUTAS DEL CONTENEDOR (LINUX)
        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        location /api/ {
            # 'backend' es el nombre del servicio en el docker-compose
            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

        # Bloque para el FRONTEND
    server {
        listen 443 ssl;
        server_name sales01.test;

        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        location / {
            proxy_pass http://frontend:5173;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}